print("YO: ¡Hola, GATITA! ¿Cómo estás hoy?")
print("Gato: Miau... no me puedo quejar.")
print("YO: ¿hace mucho frio, quierees que te ponga tu chompa?")
print("Gato: Miau miau... no te atreverias")
print("YO: Está bien, te daré tu comida favorita.")
print("Gato: ¡Miau! croquetas de pollo ya sabes.")
print("YO: ¡lo que tu digas!Bueno, voy a trabajar en eso")
print("Gato: Miau... adiós espero mi comida Miauuuuu.")